version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        env_file:
            - .env
        environment:
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
        depends_on:
            - db

    db:
        image: mysql-8.0.13
        env_file:
            - .env
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=${DB_HOST}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
        volumes:
            - ./data:/docker-entrypoint-initdb.d