version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c " python manage.py wait_for_db && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        env_file:
            - .env
        environment:
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_ROOT_PASS}
            - DB_PORT=${DB_OUTSIDE_PORT} 
        depends_on:
            - db
        links: # Link to containers in another service.
            - db:db
    db:
        image: mysql:8.0.15
        env_file:
            - .env
        restart: always
        ports:
            - ${DB_OUTSIDE_PORT}:${DB_PORT}
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
        volumes:
            - ./data:/docker-entrypoint-initdb.d
